import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync } from "node:fs";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import puppeteer from "puppeteer-core";
import { resolveBudgetPaymentPlan } from "../lib/budget-payment-plan";

const base = process.env.QUOTE_TEST_BASE_URL;
const chrome = process.env.QUOTE_CHROME_PATH ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const evidence = process.env.QUOTE_EVIDENCE_DIR ?? "/private/var/folders/jt/v4h3s4hs3wxf82mqzn6qtgg80000gn/T/opencode/ledbox-selection-preview";
const enabled = Boolean(base && /^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(base) && /^postgresql:\/\/[^@]*@(localhost|127\.0\.0\.1):\d+\/ledbox_quote_qa(?:\?|$)/.test(process.env.DATABASE_URL ?? "") && existsSync(chrome));

test("#173 A28 A30 V10 I06: provisional canonical plan, pending immutability, accept rollback and accepted document parity", { skip: !enabled, timeout: 120000 }, async () => {
  const db = new PrismaClient(), suffix = randomUUID(), org = `selection-preview-${suffix}`;
  const browser = await puppeteer.launch({ executablePath: chrome, headless: true });
  mkdirSync(evidence, { recursive: true });
  try {
    const { generatePublicToken } = await import("../lib/server/budget-portal");
    const { createSession } = await import("../lib/server/auth");
    await db.organization.create({ data: { id: org, name: "QA selection issuer", slug: org } });
    const user = await db.adminUser.create({ data: { id: randomUUID(), name: "QA owner", email: `${suffix}@example.invalid`, role: "OWNER", passwordHash: "not-a-login", autoLockEnabled: false } });
    await db.adminMembership.create({ data: { id: randomUUID(), organizationId: org, adminUserId: user.id, role: "OWNER" } });
    const client = await db.client.create({ data: { id: randomUUID(), organizationId: org, name: "QA client" } });
    const cookie = `ledbox_session=${(await createSession(user, org)).jwt}`;
    const call = (path: string, body: unknown, auth = false) => fetch(base + path, { method: "POST", headers: { "Content-Type": "application/json", "X-Forwarded-For": `qa-selection-${suffix}`, ...(auth ? { Cookie: cookie } : {}) }, body: JSON.stringify(body) });
    const plan = resolveBudgetPaymentPlan([{ label: "Reserva", type: "percent", value: 30, moment: "Al confirmar" }, { label: "Fijo", type: "fixed", value: 200000, moment: "Antes del montaje" }, { label: "Saldo", type: "remainder", moment: "Al finalizar" }], 1000001);
    assert.ok(plan.ok);
    const fixture = () => db.budget.create({ data: { id: randomUUID(), organizationId: org, clientId: client.id, title: "B1 selection", status: "SENT", publicToken: generatePublicToken(), publicTokenCreatedAt: new Date(), subtotal: 1000001, total: 1000001, installmentsJson: plan.rows, items: { create: [{ id: randomUUID(), name: "Rental", quantity: 1, days: 2, unitPrice: 300000, subtotal: 600000 }, { id: randomUUID(), name: "Service", quantity: 1, days: 1, unitPrice: 300000, subtotal: 300000 }, { id: randomUUID(), name: "Small service", quantity: 1, days: 1, unitPrice: 100001, subtotal: 100001 }] } }, include: { items: true } });
    const q = await fixture();
    const rental = q.items.find((item) => item.name === "Rental")!;
    const service = q.items.find((item) => item.name === "Service")!;
    const page = await browser.newPage();
    const previewSelector = '[data-plan-preview="provisional"]';
    for (const width of [1440, 360, 390]) {
      await page.setViewport({ width, height: 900 });
      await page.goto(`${base}/p/${q.publicToken}`, { waitUntil: "networkidle0" });
      await page.waitForSelector('button[aria-label="Retirar Rental"]');
      await page.click('button[aria-label="Retirar Rental"]');
      await page.waitForSelector(previewSelector);
      const amounts = await page.$$eval(`${previewSelector} td[data-label="Monto"]`, (nodes) => nodes.map((node) => Number(node.textContent?.replace(/\D/g, ""))));
      assert.deepEqual(amounts, [120000, 200000, 80001], `${width}: percentage/fixed/remainder preview must match400001`);
      assert.match(await page.$eval(previewSelector, (node) => node.textContent ?? ""), /provisional[\s\S]*No está aceptada/);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      await page.screenshot({ path: `${evidence}/preview-${width}.png`, fullPage: true });
      await page.click('button[aria-label="Retirar Service"]');
      await page.waitForSelector(`${previewSelector} [role="alert"]`);
      assert.equal(await page.$$eval(`${previewSelector} td[data-label="Monto"]`, (nodes) => nodes.length), 0, "invalid fixed amount must not be truncated or shown against a contradictory total");
      assert.match(await page.$eval(`${previewSelector} [role="alert"]`, (node) => node.textContent ?? ""), /superan el total|fuera del límite/);
      await page.screenshot({ path: `${evidence}/preview-invalid-${width}.png`, fullPage: true });
    }
    const snapshot = async (id: string) => {
      const row = await db.budget.findUniqueOrThrow({ where: { id }, include: { items: { orderBy: { id: "asc" } } } });
      return { status: row.status, total: row.total, subtotal: row.subtotal, discount: row.discount, plan: row.installmentsJson, approvedAt: row.approvedAt, items: row.items.map(({ id, quantity, days, excluded, subtotal }) => ({ id, quantity, days, excluded, subtotal })) };
    };
    const original = await snapshot(q.id);
    const selected = { id: rental.id, quantity: rental.quantity, days: rental.days, excluded: true };
    const propose = (token: string, items: unknown[]) => call(`/api/portal/budget/${token}/propose`, { kind: "items", name: "QA client", note: "Selection to review", items });
    for (const bad of [[selected, selected], [{ ...selected, id: randomUUID() }], [{ ...selected, unitPrice: 1 }]]) assert.equal((await propose(q.publicToken!, bad)).status, 400);
    assert.equal((await propose(q.publicToken!, [selected])).status, 200);
    assert.deepEqual(await snapshot(q.id), original, "A28 pending proposal must not mutate offer, plan or selected rows");
    const pending = await db.budgetChangeRequest.findFirstOrThrow({ where: { budgetId: q.id, status: "pending" } });
    assert.equal((await call(`/api/portal/budget/${q.publicToken}/approve`, { name: "QA client", consent: true })).status, 409);
    assert.equal((await call("/api/admin/budgets/requests", { requestId: pending.id, decision: "accept" }, true)).status, 200);
    const acceptedSelection = await snapshot(q.id);
    assert.equal(acceptedSelection.total, 400001);
    assert.deepEqual((acceptedSelection.plan as Array<{ amount: number }>).map((row) => row.amount), [120000, 200000, 80001]);
    assert.equal(acceptedSelection.items.find((item) => item.id === rental.id)?.subtotal, 0);
    assert.equal((await call(`/api/portal/budget/${q.publicToken}/approve`, { name: "QA client", consent: true })).status, 200);
    const accepted = await snapshot(q.id);
    const expected = await db.expectedPayment.findMany({ where: { budgetId: q.id }, orderBy: { installmentNumber: "asc" } });
    assert.deepEqual(expected.map((row) => row.amount), [120000, 200000, 80001]);
    assert.equal(expected.reduce((sum, row) => sum + row.amount, 0), accepted.total);
    assert.equal((await call(`/api/portal/budget/${q.publicToken}/approve`, { name: "QA client", consent: true })).status, 200);
    assert.equal(await db.expectedPayment.count({ where: { budgetId: q.id } }), 3);
    assert.deepEqual(await snapshot(q.id), accepted, "A30 retries keep accepted snapshot and ledger stable");
    const immutable = await fetch(base + "/api/admin/budgets", { method: "PATCH", headers: { "Content-Type": "application/json", Cookie: cookie }, body: JSON.stringify({ budgetId: q.id, kind: "commercial", notes: "Do not change accepted document" }) });
    assert.equal(immutable.status, 409);
    assert.deepEqual(await snapshot(q.id), accepted);
    await page.goto(`${base}/p/${q.publicToken}`, { waitUntil: "networkidle0" });
    await page.waitForSelector('[data-plan-preview="current"]');
    const finalAmounts = await page.$$eval('[data-plan-preview="current"] td[data-label="Monto"]', (nodes) => nodes.map((node) => Number(node.textContent?.replace(/\D/g, ""))));
    assert.deepEqual(finalAmounts, [120000, 200000, 80001]);
    await page.setCookie({ name: "ledbox_session", value: cookie.slice("ledbox_session=".length), url: base!, httpOnly: true });
    await page.goto(`${base}/imprimir/presupuesto/${q.id}`, { waitUntil: "networkidle0" });
    await page.waitForSelector(".budget-print-sheet");
    const printedDocument = await page.$eval(".budget-print-sheet", (node) => node.textContent ?? "");
    for (const amount of ["400.001", "120.000", "200.000", "80.001"]) assert.ok(printedDocument.includes(amount), `I06 final A4 contains ${amount}`);
    const removedText = await page.$$eval(".lbprint-table tbody tr", (rows) => rows.find((row) => row.textContent?.includes("Rental"))?.textContent ?? "");
    assert.match(removedText, /Retirado/); assert.doesNotMatch(removedText, /600\.000/);
    await page.pdf({ path: `${evidence}/post-selection-a4.pdf`, format: "A4", printBackground: true });
    const failed = await fixture();
    const failedOriginal = await snapshot(failed.id);
    const removed = failed.items.filter((item) => item.name !== "Small service").map((item) => ({ id: item.id, quantity: item.quantity, days: item.days, excluded: true }));
    assert.equal((await propose(failed.publicToken!, removed)).status, 200);
    const invalidRequest = await db.budgetChangeRequest.findFirstOrThrow({ where: { budgetId: failed.id, status: "pending" } });
    assert.equal((await call("/api/admin/budgets/requests", { requestId: invalidRequest.id, decision: "accept" }, true)).status, 400);
    assert.deepEqual(await snapshot(failed.id), failedOriginal, "A29 invalid plan rolls back all item and total edits");
    assert.equal((await db.budgetChangeRequest.findUniqueOrThrow({ where: { id: invalidRequest.id } })).status, "pending");
    assert.equal((await call("/api/admin/budgets/requests", { requestId: invalidRequest.id, decision: "reject", responseNote: "Plan incompatible; needs revision" }, true)).status, 200);
    assert.deepEqual(await snapshot(failed.id), failedOriginal, "reject does not alter the offer");
    console.log("A28/A29/A30/V10/I06: B1 provisional400001=[120000,200000,80001], no pending mutation; invalid plan rollback; accepted portal/ledger/A4 match");
  } finally { await browser.close(); await db.$disconnect(); await (await import("../lib/server/db")).db.$disconnect(); }
});
