import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { signRucConfirmation } from "../lib/server/ruc-confirmation";
import type { OwnDataResult } from "../lib/server/ruc-owndata";

const base = process.env.IDENTITY_TEST_BASE_URL;
const enabled = Boolean(base && /^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(base) && /^postgresql:\/\/[^@]*@(localhost|127\.0\.0\.1):\d+\/ledbox_identity_qa(?:\?|$)/.test(process.env.DATABASE_URL ?? ""));

test("Client/Event servidor: migración conserva historia, scope, permisos y snapshot sólo confirmado (PG local)", { skip: !enabled }, async () => {
  const db = new PrismaClient();
  const suffix = randomUUID();
  const org = `identity-${suffix}`, otherOrg = `other-${suffix}`;
  let cookie = "";
  const call = (path: string, method = "GET", body?: unknown, auth = true) => fetch(`${base}${path}`, { method, headers: { ...(auth ? { Cookie: cookie } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined });
  let ownerId = "", viewerId = "";
  try {
    const legacy = await db.client.findUnique({ where: { id: "migration-legacy-client" } });
    assert.ok(legacy, "fixture histórica debe insertarse ANTES de aplicar migración nueva");
    assert.equal(legacy.name, "Nombre histórico intacto"); assert.equal(legacy.company, "Empresa histórica intacta");
    assert.equal(legacy.tradeName, null); assert.equal(legacy.legalName, null); assert.equal(legacy.rucSnapshot, null);
    assert.deepEqual(legacy.contacts, []);
    const legacyEvent = await db.event.findUniqueOrThrow({ where: { id: "migration-legacy-event" } });
    assert.equal(legacyEvent.location, "Recinto histórico"); assert.equal(legacyEvent.city, "Ciudad histórica"); assert.equal(legacyEvent.department, null);
    await db.organization.createMany({ data: [{ id: org, slug: org, name: "Identity QA DEMO" }, { id: otherOrg, slug: otherOrg, name: "Otra empresa QA" }] });
    const owner = await db.adminUser.create({ data: { id: `owner-${suffix}`, name: "Owner QA", email: `owner-${suffix}@example.invalid`, role: "OWNER", passwordHash: "not-a-login", autoLockEnabled: false } });
    ownerId = owner.id;
    await db.adminMembership.create({ data: { id: randomUUID(), adminUserId: owner.id, organizationId: org, role: "OWNER" } });
    const { createSession } = await import("../lib/server/auth");
    cookie = `ledbox_session=${(await createSession(owner, org)).jwt}`;
    const foreign = await db.client.create({ data: { id: randomUUID(), organizationId: otherOrg, name: "Cliente privado" } });
    const foreignEvent = await db.event.create({ data: { id: randomUUID(), organizationId: otherOrg, clientId: foreign.id, name: "Evento privado" } });
    assert.equal((await call("/api/admin/clients", "POST", { tradeName: "QA DEMO" }, false)).status, 401);
    assert.equal((await call("/api/admin/clients", "POST", {})).status, 400);
    const created = await call("/api/admin/clients", "POST", { tradeName: "SCALE STRATEGY GROUP EAS", company: "Histórico no fiscal", billingEmail: " FACTURA@EXAMPLE.COM ", city: "Asunción", department: "Capital", contacts: [{ name: "Ana QA", role: "Compras", email: "ANA@EXAMPLE.COM", phone: "+595 981123456" }], address: "Calle DEMO", addressReference: "Referencia DEMO", locationUrl: "https://maps.example.invalid/demo" });
    assert.equal(created.status, 201, await created.clone().text());
    const client = (await created.json()).client;
    assert.equal(client.name, "SCALE STRATEGY GROUP EAS"); assert.equal(client.tradeName, client.name);
    assert.equal(client.legalName, null); assert.equal(client.billingEmail, "factura@example.com"); assert.equal(client.contacts[0].email, "ana@example.com");
    assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", { contactName: "Ana principal QA", website: "https://example.invalid", phone: "+54 91112345678", notes: "No borrar ni truncar" })).status, 200);
    const protectedBefore = await db.client.findUniqueOrThrow({ where: { id: client.id } });
    for (const body of [{ contactName: 123 }, { contactName: true }, { contactName: {} }, { contactName: [] }, { website: 123 }, { phone: 123 }, { notes: "x".repeat(2001) }, { contacts: [{ name: "x".repeat(121) }] }]) {
      assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", body)).status, 400);
      assert.deepEqual(await db.client.findUniqueOrThrow({ where: { id: client.id } }), protectedBefore, "PATCH rechazado no altera fila ni updatedAt");
    }
    assert.equal((await call(`/api/admin/clients/${foreign.id}`)).status, 404);
    assert.equal((await call(`/api/admin/clients/${foreign.id}`, "PATCH", { tradeName: "Filtración" })).status, 404);
    const options = (await (await call("/api/admin/clients?fields=selector")).json()).clients;
    assert.equal(options.some((c: { id: string }) => c.id === foreign.id), false);
    assert.equal(options.find((c: { id: string }) => c.id === client.id).tradeName, client.tradeName);
    const edited = await call(`/api/admin/clients/${client.id}`, "PATCH", { tradeName: "Fantasía nueva" });
    assert.equal(edited.status, 200); assert.equal((await edited.json()).client.name, "SCALE STRATEGY GROUP EAS", "PATCH fantasía no cambia name histórico");
    const result: OwnDataResult = { name: "RAZÓN SOCIAL QA DEMO EAS", fullRuc: "1234567-0", reviewRequired: true, ownData: { ruc: "1234567", dv: 0, nameOfficial: "RAZÓN SOCIAL QA DEMO EAS", equivalenceRaw: null, stateRaw: "DEMO", environment: "test", quota: { limit: 10, used: 1, remaining: 9, day: "2030-01-01", resetAfter: 60 }, provenance: { source: "dnit_official_snapshot", sourcePage: "urn:ledbox:test-fixture", publicationDate: "2030-01-01", publishedText: "", importedAt: "2030-01-01T12:00:00Z", snapshotHash: "a".repeat(64) } } };
    const signed = await signRucConfirmation(result, org, owner.id);
    const confirm = { confirmRuc: true, rucConfirmationToken: signed.confirmationToken };
    assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", { ...confirm, confirmRuc: false })).status, 400);
    const fiscal = await call(`/api/admin/clients/${client.id}`, "PATCH", confirm);
    assert.equal(fiscal.status, 200, await fiscal.clone().text());
    const saved = (await fiscal.json()).client;
    assert.equal(saved.tradeName, "Fantasía nueva"); assert.equal(saved.name, client.name); assert.equal(saved.company, "Histórico no fiscal");
    assert.equal(saved.contactName, "Ana principal QA"); assert.equal(saved.contacts[0].name, "Ana QA"); assert.equal(saved.legalName, result.name);
    assert.equal(saved.rucSnapshot.provenance.sourcePage, "urn:ledbox:test-fixture"); assert.equal(saved.rucSnapshot.lookedUpAt, signed.lookedUpAt); assert.ok(saved.rucSnapshot.confirmedAt);
    assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", { rucSnapshot: saved.rucSnapshot })).status, 400);
    const otherSigned = await signRucConfirmation(result, otherOrg, owner.id);
    assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", { ...confirm, rucConfirmationToken: otherSigned.confirmationToken })).status, 400);
    assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", { legalName: "Razón social manual" })).status, 200);
    assert.equal((await db.client.findUniqueOrThrow({ where: { id: client.id } })).rucSnapshot, null);
    const lookup = await call("/api/admin/clients/ruc", "POST", { numero: "1234567-0", confirmLookup: true });
    assert.equal(lookup.status, 503); assert.equal((await lookup.json()).manualEntryAllowed, true);
    assert.equal((await call("/api/admin/clients/ruc", "POST", { numero: "1234567-0" })).status, 400);
    assert.equal((await call("/api/admin/events", "POST", { clientId: foreign.id, name: "Cruce" })).status, 404);
    assert.equal((await call("/api/admin/events", "POST", { clientId: client.id, name: " " })).status, 400);
    const eventRes = await call("/api/admin/events", "POST", { clientId: client.id, name: "Evento QA DEMO", location: "Recinto QA", city: "Asunción", department: "Capital", startsAt: "2030-01-01T12:00:00-03:00", endsAt: "2030-01-01T18:00:00-03:00", venueContactEmail: "LUGAR@EXAMPLE.COM", responsiblePhone: "+595 981123456", modality: "Presencial", attendees: 20 });
    assert.equal(eventRes.status, 201, await eventRes.clone().text());
    const event = (await eventRes.json()).event;
    assert.equal(event.venueContactEmail, "lugar@example.com"); assert.equal(event.location, "Recinto QA"); assert.equal(event.department, "Capital");
    assert.equal((await call("/api/admin/events", "PATCH", { id: foreignEvent.id, department: "Filtración" })).status, 404);
    assert.equal((await call("/api/admin/events", "PATCH", { id: event.id, endsAt: "2029-01-01T12:00:00Z" })).status, 400);
    assert.equal((await call("/api/admin/events", "PATCH", { id: event.id, attendees: -1 })).status, 400);
    assert.equal((await call("/api/admin/events", "PATCH", { id: event.id, city: "Ciudad manual", name: "Evento editado" })).status, 200);
    const changed = await db.event.findUniqueOrThrow({ where: { id: event.id } });
    assert.equal(changed.location, "Recinto QA"); assert.equal(changed.department, null); assert.equal(changed.city, "Ciudad manual");
    const unchanged = await call("/api/admin/events", "PATCH", { id: event.id, name: changed.name });
    assert.equal((await unchanged.json()).unchanged, true);
    const events = (await (await call("/api/admin/events?fields=selector")).json()).events;
    assert.equal(events.find((e: { id: string }) => e.id === event.id).client.tradeName, "Fantasía nueva");
    assert.equal(events.some((e: { id: string }) => e.id === foreignEvent.id), false);
    assert.equal((await call(`/api/admin/clients/${client.id}`, "PATCH", { city: "Ciudad manual" })).status, 200);
    assert.equal((await db.client.findUniqueOrThrow({ where: { id: client.id } })).department, null);
    const viewer = await db.adminUser.create({ data: { id: `viewer-${suffix}`, name: "Viewer QA", email: `viewer-${suffix}@example.invalid`, role: "VIEWER", passwordHash: "not-a-login", autoLockEnabled: false } });
    viewerId = viewer.id;
    await db.adminMembership.create({ data: { id: randomUUID(), adminUserId: viewer.id, organizationId: org, role: "VIEWER" } });
    cookie = `ledbox_session=${(await createSession(viewer, org)).jwt}`;
    for (const [path, method, body] of [["/api/admin/clients", "POST", { tradeName: "Sin permiso" }], [`/api/admin/clients/${client.id}`, "PATCH", { tradeName: "Sin permiso" }], ["/api/admin/events", "POST", { clientId: client.id, name: "Sin permiso" }], ["/api/admin/events", "PATCH", { id: event.id, name: "Sin permiso" }], ["/api/admin/clients/ruc", "POST", { numero: "1234567-0", confirmLookup: true }]] as const) assert.equal((await call(path, method, body)).status, 403);
    assert.equal((await call(`/api/admin/clients/${client.id}`)).status, 200);
    const logs = await db.auditLog.findMany({ where: { organizationId: org } });
    assert.ok(logs.some(log => log.entity === "Client" && JSON.stringify(log.detail).includes("tradeName")));
    assert.ok(logs.some(log => log.entity === "Event" && JSON.stringify(log.detail).includes("department")));
    assert.doesNotMatch(JSON.stringify(logs), /confirmationToken|X-API-Key/);
  } finally {
    await db.organization.deleteMany({ where: { id: { in: [org, otherOrg] } } });
    await db.adminUser.deleteMany({ where: { id: { in: [ownerId, viewerId].filter(Boolean) } } });
    await db.$disconnect();
  }
});
