import { PDFDocument } from "pdf-lib";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";

const base = process.env.QUOTE_TEST_BASE_URL;
const localDb = process.env.DATABASE_URL ?? "";
const enabled = Boolean(base && /^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(base) && /^postgresql:\/\/[^@]*@(localhost|127\.0\.0\.1):\d+\/ledbox_quote_qa(?:\?|$)/.test(localDb));

test("quote resources HTTP integration (isolated local database only)", { skip: !enabled }, async () => {
  const db = new PrismaClient();
  const suffix = randomUUID();
  const org = `qa-${suffix}`;
  const otherOrg = `other-${suffix}`;
  const client = `client-${suffix}`;
  const inventory = `inv-${suffix}`;
  const otherInventory = `other-inv-${suffix}`;
  const document = await PDFDocument.create(); document.addPage();
  const pdf = Buffer.from(await document.save());
  let cookie = "";
  const call = async (path: string, method = "GET", body?: unknown, auth = true) => {
    const response = await fetch(`${base}${path}`, { method, headers: { ...(auth ? { Cookie: cookie } : {}), ...(body instanceof FormData ? {} : body ? { "Content-Type": "application/json" } : {}) }, body: body instanceof FormData ? body : body ? JSON.stringify(body) : undefined });
    return response;
  };
  try {
    await db.organization.createMany({ data: [{ id: org, name: "Quote QA", slug: org }, { id: otherOrg, name: "Other QA", slug: otherOrg }] });
    const user = await db.adminUser.create({ data: { id: `user-${suffix}`, name: "Quote QA", email: `qa-${suffix}@example.invalid`, role: "OWNER", passwordHash: "not-a-login", autoLockEnabled: false } });
    await db.adminMembership.create({ data: { id: `member-${suffix}`, adminUserId: user.id, organizationId: org, role: "OWNER" } });
    const { createSession } = await import("../lib/server/auth");
    const session = await createSession(user, org);
    cookie = `ledbox_session=${session.jwt}`;
    await db.client.create({ data: { id: client, organizationId: org, name: "QA client" } });
    await db.inventoryItem.createMany({ data: [{ id: inventory, organizationId: org, name: "QA product", category: "QA", listPrice: 250000 }, { id: otherInventory, organizationId: otherOrg, name: "Private other product", category: "QA" }] });
    assert.equal((await call("/api/admin/budgets/references", "POST", null)).status, 400);
    const payload = { clientId: client, title: "Quote API QA", items: [{ name: "QA product", quantity: 1, days: 1, unitPrice: 250000, costPrice: 12345, inventoryId: inventory }] };
    assert.equal((await call("/api/admin/budgets", "POST", { ...payload, items: [{ ...payload.items[0], inventoryId: otherInventory }] })).status, 400);
    const created = await call("/api/admin/budgets", "POST", payload);
    assert.equal(created.status, 201);
    const budget = (await created.json()).budget;
    assert.equal(await db.eventInventory.count({ where: { event: { organizationId: org } } }), 0, "association must not reserve stock");
    const generated = await Promise.all([call("/api/admin/budgets/token", "POST", { budgetId: budget.id, action: "ensure" }), call("/api/admin/budgets/token", "POST", { budgetId: budget.id, action: "ensure" })]);
    const codes = await Promise.all(generated.map(async (r) => (await r.json()).budget.publicToken));
    assert.equal(codes[0], codes[1], "ensure must not rotate an existing token");
    const portal = `/api/portal/budget/${codes[0]}`;
    const form = new FormData(); form.set("budgetId", budget.id); form.set("file", new File([pdf], "QA.pdf", { type: "application/pdf" }));
    const uploaded = await call("/api/admin/budgets/attachments", "POST", form);
    assert.equal(uploaded.status, 201);
    const file = (await uploaded.json()).attachment;
    assert.equal(file.clientVisible, false);
    assert.equal((await call(`${portal}/attachments/${file.id}`, "GET", undefined, false)).status, 404);
    const publish = `/api/admin/budgets/attachments/${file.id}`;
    assert.equal((await call(publish, "PATCH", { clientVisible: true }, false)).status, 401);
    assert.equal((await call(publish, "PATCH", { clientVisible: true })).status, 200);
    const shown = await call(`${portal}/attachments/${file.id}`, "GET", undefined, false);
    assert.equal(shown.status, 200);
    assert.match(shown.headers.get("content-disposition")!, /^inline;/);
    assert.match(shown.headers.get("content-security-policy")!, /sandbox/);
    assert.equal(shown.headers.get("cache-control"), "private, no-store");
    assert.equal(Buffer.from(await shown.arrayBuffer()).equals(pdf), true);
    assert.match((await call(`${portal}/attachments/${file.id}?download=1`, "GET", undefined, false)).headers.get("content-disposition")!, /^attachment;/);
    await call(publish, "PATCH", { clientVisible: false });
    assert.equal((await call(`${portal}/attachments/${file.id}`, "GET", undefined, false)).status, 404);
    const invalid = new FormData(); invalid.set("budgetId", budget.id); invalid.set("file", new File(["%PDF-1.7"], "renamed.pdf"));
    assert.equal((await call("/api/admin/budgets/attachments", "POST", invalid)).status, 400);
    const activeDocument = await PDFDocument.create(); activeDocument.addPage(); activeDocument.addJavaScript("compressed", "app.alert('unsafe')");
    const activeBytes = Buffer.from(await activeDocument.save());
    const activeForm = new FormData(); activeForm.set("budgetId", budget.id); activeForm.set("file", new File([activeBytes], "active.pdf", { type: "application/pdf" }));
    assert.equal((await call("/api/admin/budgets/attachments", "POST", activeForm)).status, 400);
    const legacyActive = await db.budgetAttachment.create({ data: { id: randomUUID(), organizationId: org, budgetId: budget.id, name: "legacy-active.pdf", mime: "application/pdf", size: activeBytes.length, data: activeBytes, uploadedByName: "QA" } });
    assert.equal((await call(`/api/admin/budgets/attachments/${legacyActive.id}`, "PATCH", { clientVisible: true })).status, 400);
    assert.equal((await db.budgetAttachment.findUniqueOrThrow({ where: { id: legacyActive.id } })).clientVisible, false);
    assert.equal((await call("/api/admin/budgets/references", "POST", { budgetId: budget.id, label: "Bad", url: "javascript:alert(1)" })).status, 400);
    const referenceResponse = await call("/api/admin/budgets/references", "POST", { budgetId: budget.id, label: "Reference", url: "https://example.invalid/reference" });
    assert.equal(referenceResponse.status, 201);
    const reference = (await referenceResponse.json()).reference;
    assert.equal((await (await call(portal, "GET", undefined, false)).json()).budget.referenceLinks.length, 0);
    await call("/api/admin/budgets/references", "PATCH", { budgetId: budget.id, id: reference.id, clientVisible: true });
    const view = (await (await call(portal, "GET", undefined, false)).json()).budget;
    assert.equal(view.referenceLinks.length, 1);
    assert.doesNotMatch(JSON.stringify(view), /costPrice|costEstimate|dailyCost|materialCost|laborCost|12345/);
    const item = await db.budgetItem.findFirstOrThrow({ where: { budgetId: budget.id } });
    const patch = { kind: "items", budgetId: budget.id, items: [{ ...payload.items[0], id: item.id, inventoryId: null }] };
    assert.equal((await call("/api/admin/budgets", "PATCH", patch)).status, 200);
    assert.equal((await db.budgetItem.findUniqueOrThrow({ where: { id: item.id } })).inventoryId, null);
    // Uploaded product photos are scoped to the quote token and its organization.
    const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1kAAAAASUVORK5CYII=", "base64");
    await db.inventoryItem.update({ where: { id: inventory }, data: { imageData: png, imageMime: "image/png" } });
    await db.budgetItem.update({ where: { id: item.id }, data: { inventoryId: inventory } });
    await db.inventoryItem.update({ where: { id: inventory }, data: { imageUrl: "https://example.invalid/manual.png" } });
    assert.equal((await (await call(portal, "GET", undefined, false)).json()).budget.items[0].imageUrl, "https://example.invalid/manual.png");
    await db.inventoryItem.update({ where: { id: inventory }, data: { imageUrl: null } });
    const pictured = (await (await call(portal, "GET", undefined, false)).json()).budget;
    assert.match(pictured.items[0].imageUrl, /\/items\/.+\/image$/);
    assert.equal((await call(pictured.items[0].imageUrl, "GET", undefined, false)).status, 200);
    await db.budgetItem.update({ where: { id: item.id }, data: { inventoryId: otherInventory } });
    assert.equal((await (await call(portal, "GET", undefined, false)).json()).budget.items[0].imageUrl, null);
    assert.equal((await call(pictured.items[0].imageUrl, "GET", undefined, false)).status, 404);
    await db.budgetItem.update({ where: { id: item.id }, data: { inventoryId: null } });
    const viewer = await db.adminUser.create({ data: { id: `viewer-${suffix}`, name: "Viewer QA", email: `viewer-${suffix}@example.invalid`, role: "VIEWER", passwordHash: "not-a-login" } });
    await db.adminMembership.create({ data: { id: `viewer-member-${suffix}`, adminUserId: viewer.id, organizationId: org, role: "VIEWER" } });
    const ownerCookie = cookie;
    cookie = `ledbox_session=${(await createSession(viewer, org)).jwt}`;
    assert.equal((await call(publish, "PATCH", { clientVisible: true })).status, 403);
    assert.equal((await call("/api/admin/budgets/references", "PATCH", { budgetId: budget.id, id: reference.id, clientVisible: false })).status, 403);
    cookie = ownerCookie;
    // Approved quote copies stay readable for payment follow-up; unapproved expiry blocks resources.
    await db.budget.update({ where: { id: budget.id }, data: { validUntil: new Date("2020-01-01") } });
    assert.equal((await call(portal, "GET", undefined, false)).status, 404);
    assert.equal((await call(`${portal}/approve`, "POST", { name: "QA client", consent: true }, false)).status, 404);
    await db.budget.update({ where: { id: budget.id }, data: { validUntil: null } });
    await call("/api/admin/budgets/token", "POST", { budgetId: budget.id, action: "revoke" });
    assert.equal((await call(portal, "GET", undefined, false)).status, 404);
    assert.equal((await call(`${portal}/attachments/${file.id}`, "GET", undefined, false)).status, 404);
    // A valid token for another quote cannot name this quote's resources.
    const foreign = await db.budget.create({ data: { id: `foreign-${suffix}`, organizationId: otherOrg, clientId: (await db.client.create({ data: { id: `foreign-client-${suffix}`, organizationId: otherOrg, name: "Other" } })).id, title: "Other", publicToken: (await import("../lib/server/budget-portal")).generatePublicToken() } });
    assert.equal((await call(`/api/portal/budget/${foreign.publicToken}/attachments/${file.id}`, "GET", undefined, false)).status, 404);
  } finally { await db.$disconnect(); await (await import("../lib/server/db")).db.$disconnect(); }
});
